In [1]:
from sklearn import svm 
import numpy as np
import matplotlib.pyplot as plt

In [19]:
X = np.array([[-2, -15],
     [-10, 2],  [-1, -29],[-10, -2],[-21, -15],[-18, -5],[-12, -18], [-15, -16],[-5, -22],[-16, -28],[-45, -13],[-11, -27],
     [ 2, -34],[-19, -21],[-4, -5],  [-18, -16],[-28, -39],[-23, -18],[-7, -7],[-23, -23],   [ 9,  5],[ 2,  39],
     [ 14,  15],[ 7,  27],[ 3,  17],[ 11,  23],[ 14,  8],[ 19,  24],[ 20,  23], [ 13,  16],
    [ 13,  16],   [ 21,  2],[ 21,  15], [ 3,  24],  [ 10,  20], [ 27,  21],[ 31,  7], [ 24,  13],[ 11,  14], [ 16,  20]])
y = np.zeros(40)
y[5:18]=1
y

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [20]:
# cross validation implmentation
step = 8
accuracy=[]
for i in range(0, len(X), step):
    X_test = X[i:i+step]
    y_test = y[i:i+step]
    
    # Constructing training set by excluding the test set
    X_train = np.concatenate((X[:i], X[i+step:]), axis=0)
    y_train = np.concatenate((y[:i], y[i+step:]), axis=0)
    model=svm.SVC(kernel ='linear')
    model.fit(X_train,y_train)
    acc=model.score(X_test,y_test)
    accuracy.append(acc)
print(accuracy)
    
#     print("X_train:", X_train)
#     print("y_train:", y_train)
average = sum(accuracy)/len(accuracy)
print(average)

[0.625, 0.625, 0.875, 1.0, 1.0]
0.825


In [7]:
# step=8
# for i in range(0,len(X),step):
    
#     X_test=X[i:i+step]
#     y_test=y[i:i+step]
#     X_train=X[X-X_test]
#     Y_train=y[y-y_test]
    
    
    
#     print(X_test)
#     print(y_test)

[[ -2 -15]
 [-10   2]
 [ -1 -29]
 [-10  -2]
 [-21 -15]
 [-18  -5]
 [-12 -18]
 [-15 -16]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[ -5 -22]
 [-16 -28]
 [-45 -13]
 [-11 -27]
 [  2 -34]
 [-19 -21]
 [ -4  -5]
 [-18 -16]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[-28 -39]
 [-23 -18]
 [ -7  -7]
 [-23 -23]
 [  9   5]
 [  2  39]
 [ 14  15]
 [  7  27]]
[0. 0. 0. 0. 1. 1. 1. 1.]
[[ 3 17]
 [11 23]
 [14  8]
 [19 24]
 [20 23]
 [13 16]
 [13 16]
 [21  2]]
[1. 1. 1. 1. 1. 1. 1. 1.]
[[21 15]
 [ 3 24]
 [10 20]
 [27 21]
 [31  7]
 [24 13]
 [11 14]
 [16 20]]
[1. 1. 1. 1. 1. 1. 1. 1.]
